sudo: false
language: node_js
node_js: '6'
cache:
  directories:
  - node_modules
notifications:
  email: false
before_script:
- npm prune
- lerna bootstrap --scope '@(function-tree|cerebral|cerebral-forms|cerebral-provider-http|cerebral-provider-forms|cerebral-router|babel-*)'
after_success:
- |
  git remote add auth https://cerebraljs:${GH_TOKEN}@github.com/cerebral/cerebral;
  git config --global user.email "cerebraljs@gmail.com";
  git config --global user.name "Cerebral JS";
  if [[ $TRAVIS_BRANCH == 'master' || $TRAVIS_PULL_REQUEST == 'true' ]]; then
    npm run coverage;
    npm run coverage:upload;
  fi
  if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
    # TODO: parse commit message for instructions to skip tagging and publishing
    git tag next -f;
    git push auth --tags -f &>/dev/null;
  fi
  if [[ $TRAVIS_BRANCH == 'next' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
    # TODO: check changed path to decide if npm publish necessary
    lerna bootstrap;
    echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > ~/.npmrc;
    lerna publish -c --npm-tag next --yes --exact;
    npm run ci;
    echo 'Website updated.'
  fi
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
