sudo: false
language: node_js
node_js: '6'
cache:
  directories:
  - node_modules
notifications:
  email: false
env:
  - TEST_MODE=serial
script:
  - npm prune
  - npm run lint
  - npm test
before_install:
  - |
    if [[ $TRAVIS_SECURE_ENV_VARS == 'true' ]]; then
      echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
    fi
after_success:
- |
  if [[ $TRAVIS_SECURE_ENV_VARS == 'true' ]]; then
    git remote add auth https://cerebraljs:${GH_TOKEN}@github.com/cerebral/cerebral;
    git config --global user.email "cerebraljs@gmail.com";
    git config --global user.name "Cerebral JS";
  fi
  if [[ $TRAVIS_BRANCH == 'master' || $TRAVIS_PULL_REQUEST == 'true' ]]; then
    npm run coverage;
    npm run coverage:upload;
  fi
  if [[ $TRAVIS_BRANCH == 'release' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
    npm run release -- --publish
    # npm run deploy && echo 'Website updated.';
  fi
  if [[ $TRAVIS_BRANCH == 'next' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
    # TODO: npm run nextRelease -- --publish
  fi
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
